sudo: false
language: node_js
node_js:
  - "5.5"
branches:
  only:
    - gh-pages
    - /.*/
before_install: npm install -g fast-xml-parser
script: xml2js -V *.html 
cache:
  directories:
    - node_modules
notifications:
  email: false
